from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

# Create your views here.
class HomePage(View):
  def get(self, request):
      context = {
          'page_title': 'Home Page',
          'page_heading': 'Welcome to the Home Page',
          'page_content': 'This is the content generated by the class-based view.',
      }
      return render(request, 'bootswatch.html', context)

class AboutPage(View):
  def get(self, request):
      context = {
          'page_title': 'About Page',
          'page_heading': 'Welcome to the About Page',
          'page_content': 'This is the content generated by the class-based view.',
      }
      return render(request, 'about.html', context)

def function_view(request):
    context = {
        'page_title': 'Function-Based View',
        'page_heading': 'Welcome to the Function-Based View',
        'page_content': 'This is the content generated by the function-based view.',
    }
    return render(request, 'function.html', context)

class ClassView(View):
    def get(self, request):
        context = {
            'page_title': 'Class-Based View',
            'page_heading': 'Welcome to the Class-Based View',
            'page_content': 'This is the content generated by the class-based view.',
        }
        return render(request, 'class.html', context)
